export const quests = [
  {
    name: 'Test 1',
    type: 'type 1',
    links: ['http://vk.com'],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, voluptas earum veritatis illum adipisci officia porro nisi quod mollitia non ullam voluptatem aliquid consequuntur? Reiciendis soluta beatae enim earum placeat perferendis eos maxime necessitatibus quod quidem ex repellat vitae fuga, adipisci saepe, provident sunt ipsum? Officia quibusdam consequatur unde esse, ipsum iusto dolor molestiae sed aliquam illo dolores sapiente ex, voluptates earum at tempore accusantium autem optio cumque hic. Unde cupiditate aperiam eligendi odit ipsam optio adipisci velit aspernatur neque quibusdam dolores totam accusantium, eaque dolorem reiciendis explicabo officia alias, nam excepturi possimus harum modi. Vel, placeat vero rem velit laborum quaerat in, sequi reprehenderit illum incidunt optio explicabo, dolores maxime nesciunt necessitatibus error deserunt! Asperiores, nobis. Quibusdam, cupiditate ex maiores perspiciatis vel assumenda nam. Aspernatur est exercitationem debitis itaque blanditiis repudiandae alias minima, aut non sint dolor pariatur doloribus odit dicta eum possimus. Nostrum amet reprehenderit at facilis alias nihil, eum quos repellat dolor ut placeat! Expedita quas nostrum necessitatibus quaerat corrupti sequi illo quae impedit, officia iste optio perspiciatis repellat quibusdam tenetur debitis ducimus, harum cum facilis laudantium commodi aliquam magnam ab accusantium eligendi. Commodi iusto iste aliquam! Molestiae ut adipisci quos amet ratione laudantium, eum minus? Facere numquam enim nam voluptate ipsam cumque quidem fugiat sapiente aspernatur, modi, nihil praesentium iusto neque quibusdam impedit quisquam excepturi, illo repudiandae expedita natus reiciendis illum. Eos numquam saepe consequatur accusantium vel nam laboriosam iste, hic corrupti repellendus aut et soluta optio ut nihil culpa molestiae commodi ipsa, earum excepturi ipsam ipsum voluptates quidem pariatur? Aliquid vero quaerat amet doloremque, labore autem perferendis atque quae et ipsum facilis saepe impedit nulla aperiam sit debitis necessitatibus totam. Nam nostrum cumque magni modi aspernatur nemo magnam eveniet vitae maxime iusto! Inventore corporis nulla, minima voluptas autem rem dolore iste maiores deserunt temporibus alias?',
    solution: 'asdsad',
  },
  {
    name: 'Test 1',
    type: 'type 1',
    links: ['http://vk.com'],
    description: 'cerf',
    solution: 'asdsad',
  },
  {
    name: 'Test 1',
    type: 'type 1',
    links: ['http://vk.com'],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, voluptas earum veritatis illum adipisci officia porro nisi quod mollitia non ullam voluptatem aliquid consequuntur? Reiciendis soluta beatae enim earum placeat perferendis eos maxime necessitatibus quod quidem ex repellat vitae fuga, adipisci saepe, provident sunt ipsum? Officia quibusdam consequatur unde esse, ipsum iusto dolor molestiae sed aliquam illo dolores sapiente ex, voluptates earum at tempore accusantium autem optio cumque hic. Unde cupiditate aperiam eligendi odit ipsam optio adipisci velit aspernatur neque quibusdam dolores totam accusantium, eaque dolorem reiciendis explicabo officia alias, nam excepturi possimus harum modi. Vel, placeat vero rem velit laborum quaerat in, sequi reprehenderit illum incidunt optio explicabo, dolores maxime nesciunt necessitatibus error deserunt! Asperiores, nobis. Quibusdam, cupiditate ex maiores perspiciatis vel assumenda nam. Aspernatur est exercitationem debitis itaque blanditiis repudiandae alias minima, aut non sint dolor pariatur doloribus odit dicta eum possimus. Nostrum amet reprehenderit at facilis alias nihil, eum quos repellat dolor ut placeat! Expedita quas nostrum necessitatibus quaerat corrupti sequi illo quae impedit, officia iste optio perspiciatis repellat quibusdam tenetur debitis ducimus, harum cum facilis laudantium commodi aliquam magnam ab accusantium eligendi. Commodi iusto iste aliquam! Molestiae ut adipisci quos amet ratione laudantium, eum minus? Facere numquam enim nam voluptate ipsam cumque quidem fugiat sapiente aspernatur, modi, nihil praesentium iusto neque quibusdam impedit quisquam excepturi, illo repudiandae expedita natus reiciendis illum. Eos numquam saepe consequatur accusantium vel nam laboriosam iste, hic corrupti repellendus aut et soluta optio ut nihil culpa molestiae commodi ipsa, earum excepturi ipsam ipsum voluptates quidem pariatur? Aliquid vero quaerat amet doloremque, labore autem perferendis atque quae et ipsum facilis saepe impedit nulla aperiam sit debitis necessitatibus totam. Nam nostrum cumque magni modi aspernatur nemo magnam eveniet vitae maxime iusto! Inventore corporis nulla, minima voluptas autem rem dolore iste maiores deserunt temporibus alias?',
    solution: 'asdsad',
  }
];

